-- Seed data compiled from verified sources. Replace or extend with your full dataset.

insert into competitions (
  name, category, domain_focus, stage_fit, eligibility_age_min, eligibility_age_max,
  team_size_max, requires_demo, requires_plan, judging_focus, deadline,
  application_link, location, notes, data_status
) values
  (
    'Blue Ocean Student Entrepreneur Competition',
    'Entrepreneurship',
    'Business, Innovation',
    'Pitch',
    14,
    18,
    5,
    false,
    false,
    'Innovation, market potential, pitch clarity',
    '2026-02-22',
    'https://blueoceancompetition.org/',
    'Virtual',
    'High school virtual pitch competition. Team up with up to four friends.',
    'verified'
  ),
  (
    'St. John''s University High School Pitch Competition',
    'Entrepreneurship',
    'Business, Innovation',
    'Pitch',
    14,
    18,
    3,
    false,
    true,
    'Creativity, feasibility, impact',
    '2026-03-16',
    'https://www.stjohns.edu/academics/schools/peter-j-tobin-college-business/tobins-experiential-opportunities/high-school-pitch-competition-2026',
    'Queens, NY',
    'Open to all high school students; teams of up to 3.',
    'verified'
  ),
  (
    'tecBRIDGE High School Business Plan Competition',
    'Business Plan',
    'STEAM',
    'Business Plan',
    14,
    18,
    null,
    false,
    true,
    'Business plan, research, presentation',
    '2026-03-13',
    'https://www.tecbridgepa.org/high-school-business-plan-competition1382e2ca',
    'Northeastern Pennsylvania',
    'Open to HS students in listed PA counties.',
    'verified'
  ),
  (
    'Wisconsin High School Business Model Competition',
    'Entrepreneurship',
    'Business, Innovation',
    'Pitch',
    15,
    18,
    3,
    false,
    false,
    'Idea quality, pitch, feasibility',
    null,
    'https://www.uwosh.edu/cei/competitions/hs-pitch/',
    'Wisconsin',
    'Future events TBD; team up to 3.',
    'verified'
  ),
  (
    'Maryland High School Business Plan Competition',
    'Business Plan',
    'Business, Entrepreneurship',
    'Business Plan',
    null,
    null,
    5,
    false,
    true,
    'Executive summary, venture quality',
    null,
    'https://www.competitionsciences.org/competitions/maryland-high-school-business-plan-competition/',
    'Maryland',
    'Eligibility: high school freshmen-juniors in Maryland.',
    'verified'
  ),
  (
    'Conrad Challenge',
    'Innovation',
    'Aerospace, Cyber, Energy, Health',
    'Innovation',
    13,
    18,
    5,
    false,
    true,
    'Innovation, impact, feasibility',
    null,
    'https://www.conradchallenge.org/',
    'Global',
    'Teams of 2-5 students, ages 13-18.',
    'verified'
  ),
  (
    'Diamond Challenge',
    'Entrepreneurship',
    'Business, Social Innovation',
    'Pitch',
    14,
    18,
    4,
    false,
    true,
    'Innovation, venture quality, pitch',
    null,
    'https://diamondchallenge.org/competition/',
    'Global',
    'Teams of 2-4 high school students, ages 14-18.',
    'verified'
  ),
  (
    'FIRST Robotics Competition (FRC)',
    'Robotics',
    'Robotics, Engineering, STEM',
    'Prototype',
    14,
    18,
    null,
    true,
    false,
    'Engineering design, teamwork, robot performance',
    null,
    'https://www.firstinspires.org/robotics/frc',
    'Global',
    'Grades 9-12; build and compete with industrial-sized robots.',
    'verified'
  ),
  (
    'Science Olympiad Division C',
    'STEM',
    'Science, Engineering',
    'Research',
    14,
    18,
    15,
    false,
    false,
    'Team events across science disciplines',
    null,
    'https://www.scscioly.org/division-c',
    'State/National',
    'Division C is grades 9-12, teams up to 15 students.',
    'verified'
  ),
  (
    'SkillsUSA Championships',
    'CTE',
    'Skilled Trades, Leadership',
    'Skills',
    null,
    null,
    null,
    true,
    false,
    'Technical skills and leadership',
    null,
    'https://www.skillsusa.org/competitions/',
    'National',
    'National showcase with 100+ events.',
    'verified'
  ),
  (
    'HOSA Competitive Events',
    'Health',
    'Health, Biomedical',
    'Competition',
    null,
    null,
    null,
    false,
    false,
    'Health science competencies',
    null,
    'https://hosa.org/competition/',
    'National',
    'Competitive events for HOSA members.',
    'verified'
  ),
  (
    'DECA Competitive Events',
    'Business',
    'Marketing, Finance, Hospitality',
    'Competition',
    null,
    null,
    null,
    false,
    false,
    'Business case and role-play events',
    null,
    'https://www.deca.org/compete',
    'National',
    'DECA competitive events for high school members.',
    'verified'
  ),
  (
    'FBLA High School Competitive Events',
    'Business',
    'Business, Career Development',
    'Competition',
    null,
    null,
    null,
    false,
    false,
    'Business and career skills',
    null,
    'https://www.fbla.org/high-school/competitive-events/',
    'National',
    'High school competitive events for FBLA members.',
    'verified'
  ),
  (
    'Technology Student Association (TSA) High School Competitions',
    'STEM',
    'Technology, Engineering, STEM',
    'Competition',
    null,
    null,
    null,
    false,
    false,
    'STEM competitive events',
    null,
    'https://tsaweb.org/',
    'National',
    'TSA offers high school competitions nationwide.',
    'verified'
  ),
  (
    'K12 Innovation Challenge',
    'Innovation',
    'Education, Innovation',
    'Pitch',
    11,
    18,
    3,
    true,
    false,
    'Creativity, impact, pitch clarity',
    '2026-02-09',
    'https://enrichment.k12.com/innovation-challenge/',
    'United States',
    'Grades 6-12. Video pitch required.',
    'verified'
  ),
  (
    'A.H. Nickless Innovation Award',
    'STEM',
    'STEM, Innovation',
    'Research',
    13,
    18,
    5,
    false,
    true,
    'Problem solving, innovation, STEM impact',
    '2025-10-31',
    'https://ahninnovationaward.com/',
    'Great Lakes Bay Region, MI',
    'Teams of 2-5 high school students in Bay, Midland, Saginaw, and Tuscola counties.',
    'verified'
  ),
  (
    'Harvard VCG High School Pitch Competition',
    'Entrepreneurship',
    'Business, Innovation',
    'Pitch',
    14,
    19,
    2,
    true,
    true,
    'Pitch clarity, market opportunity, execution strategy',
    null,
    'https://www.harvardvcg.org/hspitchcomp',
    'Virtual',
    'Open to high school students and rising college freshmen; teams up to 2.',
    'verified'
  ),
  (
    'High School Science Pitch (HSSP)',
    'STEM',
    'Science, Engineering, Research',
    'Pitch',
    null,
    null,
    null,
    true,
    false,
    'Scientific process, clarity, impact',
    null,
    'https://hs-sp.org/',
    'Virtual',
    'Two-round science pitch and showcase format.',
    'verified'
  );

insert into pitch_opportunities (
  name, type, audience, requires_demo, requires_plan, how_to_apply,
  eligibility_age_min, eligibility_age_max, team_size_max, relevance_tags, data_status
) values
  (
    'Blue Ocean Student Entrepreneur Competition',
    'Virtual Pitch',
    'High school founders',
    false,
    false,
    'Submit a 5-minute video pitch and registration details.',
    14,
    18,
    5,
    'Entrepreneurship, Business, Innovation',
    'verified'
  ),
  (
    'St. John''s University High School Pitch Competition',
    'Pitch Event',
    'High school students',
    false,
    true,
    'Register online; pitch March 16, 2026.',
    14,
    18,
    3,
    'Entrepreneurship, Pitch, Business',
    'verified'
  ),
  (
    'Wisconsin High School Business Model Competition',
    'Pitch Event',
    'Wisconsin high school students',
    false,
    false,
    'Submit online application; finalists pitch in person.',
    15,
    18,
    3,
    'Entrepreneurship, Business, Pitch',
    'verified'
  ),
  (
    'Conrad Challenge Power Pitch Stage',
    'Pitch Event',
    'Finalist teams',
    true,
    true,
    'Finalists invited to pitch at Innovation Summit.',
    13,
    18,
    5,
    'Innovation, Entrepreneurship',
    'verified'
  ),
  (
    'Diamond Challenge Pitch Round',
    'Pitch Event',
    'High school teams',
    false,
    true,
    'Submit concept and pitch round format.',
    14,
    18,
    4,
    'Entrepreneurship, Pitch',
    'verified'
  ),
  (
    'K12 Innovation Challenge',
    'Video Pitch',
    'Grades 6-12',
    true,
    false,
    'Submit a video pitch online.',
    11,
    18,
    3,
    'Education, Innovation, Pitch',
    'verified'
  ),
  (
    'Harvard VCG High School Pitch Competition',
    'Pitch Event',
    'High school students',
    true,
    true,
    'Submit a business plan and video pitch.',
    14,
    19,
    2,
    'Entrepreneurship, Pitch, Business',
    'verified'
  ),
  (
    'High School Science Pitch (HSSP)',
    'Science Pitch',
    'High school researchers',
    true,
    false,
    'Submit a 1-3 minute video pitch.',
    null,
    null,
    null,
    'Science, Research, Pitch',
    'verified'
  );
